server:
  name: ${SERVER_NAME:chat-server}
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  channel: ${REDIS_CHANNEL:group-chat}