apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: mysql-configmap
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: minikube-local-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: minikube-local-storage
          persistentVolumeClaim:
            claimName: mysql-pvc