server:
  name: ${SERVER_NAME:datastore}
  port: ${SERVER_PORT:8080}


datastore:
  postgres:
    host: ${POSTGRESQL_HOST:127.0.0.1}
    port: ${POSTGRES_PORT:5432}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    db: ${POSTGRES_DB:postgres}
    sslMode: ${POSTGRESQL_USE_SSL:disable}
  mongo:
    host: ${MONGODB_HOST:127.0.0.1}
    port: ${MONGODB_PORT:27017}
    db: ${MONGODB_DB:mongo}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_HOST:6379}