---
version: "3.8"
services:
  # all the datastore workers
  datastore-worker:
    image: abhishek1009/datastore:latest
    container_name: datastore-worker
    environment:
      - SERVER_NAME=datastore-worker
      - SERVER_ADDRESS=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    networks:
      - datastore-network
    depends_on:
      - redis
  haproxy:
    image: haproxy
    container_name: datastore
    depends_on:
      - datastore-worker
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    networks:
      - datastore-network
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - datastore-network
networks:
  datastore-network: